importdata <- read.csv("wine.csv", header=TRUE)
head(importdata)
summary(importdata)
model1= lm(Price~Age, data=importdata)
print(model1)
summary(model1)
model2= lm(Price~AGST, data=importdata)
summary(model2)
sse2= sum(model2$residuals^2)
(sse2)
model3= lm(Price~AGST+HarvestRain, data=importdata)
summary(model3)
(sse3=sum(model3$residuals^2))
model4= lm(Price~AGST+HarvestRain+Age+WinterRain+FrancePop, data=importdata)
summary(model4)
(sse4=sum(model4$residuals^2))
(model5=lm(Price~AGST+HarvestRain+Age+WinterRain, data=importdata))
summary(model5)
plot(model5)
(cor(importdata$Age, importdata$FrancePop))
cor(importdata)
data<-read.csv("Wine_Test.csv", header=TRUE)
head(data)
(predictTest<- predict(model5,newdata=data))
?newdata
